server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking


gemini:
  api:
    # Set GEMINI_API_URL to override; default points to Gemini 1.5 Flash text endpoint
    # Examples:
    # - https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent
    # - https://generativelanguage.googleapis.com/v1/models/gemini-1.5-pro:generateContent
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent}
    # Do NOT hardcode secrets. Provide via environment variable GEMINI_API_KEY.
    key: ${GEMINI_API_KEY:}