spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  # Temporarily disable Spring Cloud/Boot compatibility check to allow Boot 3.5.x to run with current Cloud libs
  cloud:
    compatibility-verifier:
      enabled: false