spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_user_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibername.ddl-auto=update
spring.jpa.database-platform:org.hibernate.dialect.PostgreSQLDialect
server.port=8081
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=localhost
#Sab service same machine pe ho toh:
# Tumko eureka.instance.hostname=localhost likhna hi padta hai!
# Taaki Eureka dashboard mein sab localhost ke naam se aaye.

#If services are on different machines:
# Tum localhost nahi likh sakte.
# Tumko real ...IP or Hostname IP ka friendly name ---Computer hostname ko IP mein badalta hai
# DNS ya hosts file use karke--- likhna padta hai jo dusri machine se accessible ho.
# In this way........  eureka.instance.hostname=192.168.1.10

#Why
# Eureka needs to tell other services where to call.
# If you keep localhost, it means call yourself.
# But on different machines, localhost always means that machine itself.
